template:
  - 'gnome-shell.less'
  - 'images.sh'

less:
  'gnome-shell.less'

run:
  'images.sh'

install:
  src: 
    - 'gnome-shell.css'
    - 'assets'
  dest:
    '/usr/share/gnome-shell/theme'

load:
  "gdbus call --session --dest org.gnome.Shell --object-path /org/gnome/Shell --method org.gnome.Shell.Eval 'Main.loadTheme();'"