template:
  'colors.sh'

install:
  src: 
    'colors.sh'
  dest:
    '/home/etn/.config'
    # TODO bug when I set ~ instead of the absolute path
    # Using $LOGNAME, but I am not sure if it's correct

# TODO you need to add this line to your .zshrc / .bashrc :
# source $HOME/.config/colors.sh

# load:
  # 'source /home/etn/.zshrc'
  # './colortest'